services:
  gtnh:
    image: dudesw575/mc-gtnh:latest
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
    volumes:
      - gtnh-data:/minecraft

volumes:
  gtnh-data:
